baseURL = "https://jarodl.am/cookbook/"
languageCode = "en-us"
title = "Lam Family Cookbook"
theme = "hyde"

[Menus]
  main = [
  ]

[params]
  description = "A collection of family recipes and more."
  themeColor = "theme-base-08"