baseURL = "https://jarodl.am/cookbook/"
languageCode = "en-us"
title = "Lam Family Cookbook"
theme = "hyde"
summaryLength = 30

[Menus]
  main = [
    {Name = "Categories", URL = "/categories"} 
  ]

[params]
  description = "A collection of family recipes and more."
  themeColor = "theme-base-08"